### PR TITLE
Add support for Symfony 5

### PR DESCRIPTION
**Pull request by gnutix**

### CODE REVIEW

**Review by williamdes — APPROVED** [review]

**Review by MauricioFauth — APPROVED** [review]

**Comment by williamdes** [comment]
Thank you @gnutix for the PR !
https://github.com/phpmyadmin/motranslator/blob/master/CHANGELOG.md#unreleased--

**Comment by gnutix** [comment]
@williamdes  Thanks! Any chance you might create a new release soon ? (I don't really like deploying our application to production with "dev-master" dependencies)

**Comment by ibennetch** [comment]
I can definitely perform the new release of motranslator soon.

**Comment by ibennetch** [comment]
Thanks for the work, motranslator 5.0.0 is released.

**Pull request merged**
